stages:
  - deploy

test:
  image: $CI_REGISTRY/autowp/runner-base-image
  stage: deploy
  script:
    - helm dependency update
    - helm dependencies build
    - helm lint

    - kubectl config set-credentials autowp-gitlab --token="$K8S_TOKEN"
    - kubectl config set-context --current --user=autowp-gitlab

    - helm diff -n autowp upgrade --install autowp . --reuse-values
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment:
    name: production
    url: https://www.wheelsage.org/
