stages:
  - deploy

deploy:
  image: $CI_REGISTRY/autowp/runner-base-image
  stage: deploy
  script:
    - helm dependency update
    - helm lint

    - helm -n autowp upgrade autowp . --reuse-values
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment:
    name: production
    url: https://www.wheelsage.org/
