sentry:
  dsn: {{ .Values.auth.sentry.dsn }}
  environment: production
migrations:
  dsn: postgres://auth:password@auth-postgres/auth?sslmode=disable
oauth:
  dsn: postgres://auth:password@auth-postgres:5432/auth?sslmode=disable
  secret: {{ .Values.auth.secret }}
  user_store:
    dsn: {{ .Values.mysql.username }}:{{ .Values.mysql.password }}@tcp(mysql:3306)/autowp?charset=utf8&parseTime=true&loc=UTC
    salt: {{ .Values.usersSalt }}
services:
  google:
    client_id: {{ .Values.google.clientId }}
    client_secret: {{ .Values.google.clientSecret }}
  facebook:
    client_id: {{ .Values.facebook.clientId }}
    client_secret: {{ .Values.facebook.clientSecret }}
  vk:
    client_id: {{ .Values.vk.clientId }}
    client_secret: {{ .Values.vk.clientSecret }}
