apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autowp.goautowp.autoban.fullname" . | quote }}
spec:
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: goautowp-autoban
  replicas: 1
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: goautowp-autoban
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/goautowp/*").AsConfig . ) | sha256sum }}
    spec:
      {{- include "autowp.imagePullSecrets" . | nindent 6 }}
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ include "autowp.goautowp.fullname" . | quote }}
          name: config
        - name: tmp
          emptyDir: {}
      containers:
        - name: goautowp-autoban
          image: {{ include "autowp.goautowp.image" . }}
          imagePullPolicy: {{ .Values.goautowp.image.pullPolicy | quote }}
          args:
            - serve
            - --autoban
          ports:
            - name: metrics
              containerPort: 2112
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml
              readOnly: true
            - mountPath: /tmp
              name: tmp
          resources:
            limits:
              memory: 5Gi
              cpu: 4000m
            requests:
              memory: 10M
              cpu: 50m
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 101
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - goautowp-autoban
              weight: 100
