apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autowp.goautowp.listen-monitoring-amqp.fullname" . | quote }}
spec:
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: goautowp-listen-monitoring-amqp
  replicas: 2
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: goautowp-listen-monitoring-amqp
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/{goautowp,casbin}/*").AsConfig . ) | sha256sum }}
    spec:
      {{- include "autowp.imagePullSecrets" . | nindent 6 }}
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ include "autowp.goautowp.fullname" . | quote }}
          name: config
        - configMap:
            defaultMode: 420
            name: casbin
          name: casbin
      containers:
        - name: goautowp-listen-monitoring-amqp
          image: {{ include "autowp.goautowp.image" . }}
          imagePullPolicy: {{ .Values.goautowp.image.pullPolicy | quote }}
          args:
            - listen-monitoring-amqp
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml
              readOnly: true
            - mountPath: /model.conf
              name: casbin
              subPath: model.conf
              readOnly: true
            - mountPath: /policy.csv
              name: casbin
              subPath: policy.csv
              readOnly: true
          resources:
            limits:
              memory: 5Gi
              cpu: 4000m
            requests:
              memory: 10M
              cpu: 50m
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 101
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - goautowp-listen-monitoring-amqp
              weight: 100