apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autowp.backend.fullname" . | quote }}
  labels:
    app.kubernetes.io/component: backend
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: "nginx required temporary files for buffering"
    ignore-check.kube-linter.io/run-as-non-root: "php-fpm is running from root"
    ignore-check.kube-linter.io/latest-tag: "allow to use latest for deprecated image"
spec:
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  replicas: 2
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: backend
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/{backend,casbin}/*").AsConfig . ) | sha256sum }}
    spec:
      {{- include "autowp.imagePullSecrets" . | nindent 6 }}
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ include "autowp.backend.fullname" . | quote }}
          name: config
        - configMap:
            defaultMode: 420
            name: casbin
          name: casbin
      containers:
        - name: php-fpm
          image: {{ include "autowp.backend.image" . }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy | quote }}
          ports:
            - name: php-fpm-port
              containerPort: 9000
          volumeMounts:
            - mountPath: /app/config/autoload/local.php
              name: config
              subPath: local.php
              readOnly: true
            - mountPath: /app/module/Application/config/model.conf
              name: casbin
              subPath: model.conf
              readOnly: true
            - mountPath: /app/module/Application/config/policy.csv
              name: casbin
              subPath: policy.csv
              readOnly: true
          resources:
            limits:
              memory: 5Gi
              cpu: 4000m
            requests:
              memory: 10M
              cpu: 50m
        - name: nginx
          image: {{ include "autowp.backend.nginx.image" . }}
          imagePullPolicy: {{ .Values.backend.nginx.image.pullPolicy | quote }}
          ports:
            - name: app-port
              containerPort: 8080
          resources:
            limits:
              memory: 5Gi
              cpu: 4000m
            requests:
              memory: 10M
              cpu: 50m
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - backend
              weight: 100
