apiVersion: batch/v1
kind: CronJob
metadata:
  name: midnight
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: "laminas application required temporary files for cache"
    ignore-check.kube-linter.io/run-as-non-root: "php-fpm is running from root"
    ignore-check.kube-linter.io/latest-tag: "allow to use latest for deprecated image"
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ (tpl (.Files.Glob "configs/{backend,casbin}/*").AsConfig . ) | sha256sum }}
        spec:
          {{- include "autowp.imagePullSecrets" . | nindent 10 }}
          volumes:
          - configMap:
              defaultMode: 420
              name: {{ include "autowp.backend.fullname" . | quote }}
            name: config
          - configMap:
              defaultMode: 420
              name: casbin
            name: casbin
          containers:
            - name: midnight
              image: {{ include "autowp.backend.image" . }}
              imagePullPolicy: {{ .Values.backend.image.pullPolicy | quote }}
              args:
                - ./zf
                - cron
                - midnight
              volumeMounts:
                - mountPath: /app/config/autoload/local.php
                  name: config
                  subPath: local.php
                  readOnly: true
                - mountPath: /app/module/Application/config/model.conf
                  name: casbin
                  subPath: model.conf
                  readOnly: true
                - mountPath: /app/module/Application/config/policy.csv
                  name: casbin
                  subPath: policy.csv
                  readOnly: true
              resources:
                limits:
                  memory: 5Gi
                  cpu: 4000m
                requests:
                  memory: 10M
                  cpu: 50m
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
