rest:
  mode: "debug"
  listen: ":8080"
sentry:
  dsn: {{ .Values.goautowp.sentry.dsn | quote }}
  environment: production
migrations:
  dir: ./migrations
  dsn: "mysql://{{ .Values.mysql.username }}:{{ .Values.mysql.password }}@tcp(mysql)/autowp?charset=utf8mb4&parseTime=true&loc=UTC"
duplicate_finder:
  rabbitmq: amqp://guest:guest@{{ include "autowp.rabbitmq.fullname" . }}:5672/
  queue: duplicate_finder
dsn: "{{ .Values.mysql.username }}:{{ .Values.mysql.password }}@tcp(mysql:3306)/autowp?charset=utf8mb4&parseTime=true&loc=UTC"
file_storage:
  bucket: files
  s3:
    endpoints:
      {{- range .Values.s3.endpoints }}
      - {{ . | quote}}
      {{- end }}
oauth:
  secret: {{ .Values.auth.secret | quote }}
