apiVersion: v1
data: {{ (tpl (.Files.Glob "configs/auth/*").AsConfig . ) | nindent 2 }}
kind: ConfigMap
metadata:
  name: auth

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 3
  template:
    metadata:
      labels:
        app: auth
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/auth/*").AsConfig . ) | sha256sum }}
    spec:
      volumes:
        - configMap:
            defaultMode: 420
            name: auth
          name: config
      containers:
        - name: auth
          image: autowp/auth
          imagePullPolicy: Always
          ports:
            - name: app-port
              containerPort: 80
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml
              readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
spec:
  ports:
    - name: app-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: auth
  sessionAffinity: None
  type: ClusterIP
