apiVersion: v1
data: {{ (tpl (.Files.Glob "configs/auth-postgres/*").AsConfig . ) | nindent 2 }}
kind: ConfigMap
metadata:
  name: auth-postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres
spec:
  selector:
    matchLabels:
      app: auth-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-postgres
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/auth-postgres/*").AsConfig . ) | sha256sum }}
    spec:
      volumes:
        - name: auth-postgres
          persistentVolumeClaim:
            claimName: auth-postgres
      containers:
        - name: auth-postgres
          image: postgres:12
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_USER
              value: "auth"
            - name: POSTGRES_DB
              value: "auth"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: auth-postgres

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-postgres
  name: auth-postgres
spec:
  ports:
    - name: app-port
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: auth-postgres
  sessionAffinity: None
  type: ClusterIP
