apiVersion: v1
data: {{ (tpl (.Files.Glob "configs/backend/*").AsConfig . ) | nindent 2 }}
kind: ConfigMap
metadata:
  name: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/backend/*").AsConfig . ) | sha256sum }}
    spec:
      volumes:
        - configMap:
            defaultMode: 420
            name: backend
          name: config
      containers:
        - name: backend
          image: autowp/autowp
          imagePullPolicy: Always
          ports:
            - name: app-port
              containerPort: 80
          volumeMounts:
            - mountPath: /app/config/autoload/local.php
              name: config
              subPath: local.php
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  ports:
    - name: app-port
      port: 80
      protocol: TCP
      targetPort: app-port
  selector:
    app: backend
  sessionAffinity: None
  type: ClusterIP
