apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: "nginx required temporary files for buffering"
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: frontend
          image: "registry.pereslegin.ru/autowp/frontend:v1.80.0"
          imagePullPolicy: Always
          ports:
            - name: app-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: app-port
              httpHeaders:
                - name: X-Health
                  value: "Kubernetes-Health"
                - name: Host
                  value: "www.autowp.ru"
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: app-port
              httpHeaders:
                - name: X-Health
                  value: "Kubernetes-Health"
                - name: Host
                  value: "www.autowp.ru"
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
          resources:
            limits:
              memory: 5Gi
              cpu: 4000m
            requests:
              memory: 10M
              cpu: 50m
      securityContext:
        runAsNonRoot: true
        fsGroup: 101
        runAsUser: 101
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - frontend
              weight: 100
