apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: autowp/autowp-frontend
        imagePullPolicy: Always
        ports:
        - name: app-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: app-port
            httpHeaders:
              - name: X-Health
                value: "Kubernetes-Health"
              - name: Host
                value: "www.autowp.ru"
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: app-port
            httpHeaders:
              - name: X-Health
                value: "Kubernetes-Health"
              - name: Host
                value: "www.autowp.ru"
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
    - name: app-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP

