apiVersion: v1
data: {{ (tpl (.Files.Glob "configs/goautowp/*").AsConfig . ) | nindent 2 }}
kind: ConfigMap
metadata:
  name: goautowp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goautowp
spec:
  selector:
    matchLabels:
      app: goautowp
  replicas: 3
  template:
    metadata:
      labels:
        app: goautowp
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/goautowp/*").AsConfig . ) | sha256sum }}
    spec:
      volumes:
        - configMap:
            defaultMode: 420
            name: goautowp
          name: config
      containers:
        - name: goautowp
          image: autowp/goautowp
          imagePullPolicy: Always
          ports:
            - name: app-port
              containerPort: 8080
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: goautowp
  name: goautowp
spec:
  ports:
    - name: app-port
      port: 80
      protocol: TCP
      targetPort: app-port
  selector:
    app: goautowp
  sessionAffinity: None
  type: ClusterIP
