apiVersion: batch/v1
kind: CronJob
metadata:
  name: goautowp-scheduler-midnight
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ (tpl (.Files.Glob "configs/{goautowp,casbin}/*").AsConfig . ) | sha256sum }}
        spec:
          imagePullSecrets:
            - name: gitlab-registry
          volumes:
            - configMap:
                defaultMode: 420
                name: goautowp
              name: config
            - configMap:
                defaultMode: 420
                name: casbin
              name: casbin
          containers:
            - name: goautowp-scheduler-midnight
              image: registry.pereslegin.ru/autowp/goautowp:v1.32.0
              imagePullPolicy: Always
              args:
                - scheduler-midnight
              volumeMounts:
                - mountPath: /config.yaml
                  name: config
                  subPath: config.yaml
                  readOnly: true
                - mountPath: /model.conf
                  name: casbin
                  subPath: model.conf
                  readOnly: true
                - mountPath: /policy.csv
                  name: casbin
                  subPath: policy.csv
                  readOnly: true
              resources:
                limits:
                  memory: 5Gi
                  cpu: 4000m
                requests:
                  memory: 10M
                  cpu: 50m
              securityContext:
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 101
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
