apiVersion: batch/v1
kind: CronJob
metadata:
  name: goautowp-scheduler-hourly
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ (tpl (.Files.Glob "configs/{goautowp,casbin}/*").AsConfig . ) | sha256sum }}
        spec:
          imagePullSecrets:
            - name: gitlab-registry
          volumes:
            - configMap:
                defaultMode: 420
                name: goautowp
              name: config
            - configMap:
                defaultMode: 420
                name: casbin
              name: casbin
          containers:
            - name: goautowp-scheduler-hourly
              image: registry.pereslegin.ru/autowp/goautowp:v1.17.0
              imagePullPolicy: Always
              args:
                - scheduler-hourly
              volumeMounts:
                - mountPath: /config.yaml
                  name: config
                  subPath: config.yaml
                  readOnly: true
                - mountPath: /model.conf
                  name: casbin
                  subPath: model.conf
                  readOnly: true
                - mountPath: /policy.csv
                  name: casbin
                  subPath: policy.csv
                  readOnly: true
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
