apiVersion: apps/v1
kind: Deployment
metadata:
  name: goautowp-serve-private
spec:
  selector:
    matchLabels:
      app: goautowp-serve-private
  replicas: 3
  template:
    metadata:
      labels:
        app: goautowp-serve-private
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/{goautowp,casbin}/*").AsConfig . ) | sha256sum }}
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      volumes:
        - configMap:
            defaultMode: 420
            name: goautowp
          name: config
        - configMap:
            defaultMode: 420
            name: casbin
          name: casbin
      containers:
        - name: goautowp-serve-private
          image: registry.pereslegin.ru/autowp/goautowp:v1.32.4
          imagePullPolicy: Always
          args:
            - serve-private
          ports:
            - name: app-port
              containerPort: 8081
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml
              readOnly: true
            - mountPath: /model.conf
              name: casbin
              subPath: model.conf
              readOnly: true
            - mountPath: /policy.csv
              name: casbin
              subPath: policy.csv
              readOnly: true
          resources:
            limits:
              memory: 5Gi
              cpu: 4000m
            requests:
              memory: 10M
              cpu: 50m
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 101
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - goautowp-serve-private
              weight: 100

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: goautowp-serve-private
  name: goautowp-serve-private
spec:
  ports:
    - name: app-port
      port: 8081
      protocol: TCP
      targetPort: app-port
  selector:
    app: goautowp-serve-private
  type: ClusterIP