apiVersion: apps/v1
kind: Deployment
metadata:
  name: goautowp-autoban
spec:
  selector:
    matchLabels:
      app: goautowp-autoban
  replicas: 1
  template:
    metadata:
      labels:
        app: goautowp-autoban
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/{goautowp,casbin}/*").AsConfig . ) | sha256sum }}
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      volumes:
        - configMap:
            defaultMode: 420
            name: goautowp
          name: config
        - configMap:
            defaultMode: 420
            name: casbin
          name: casbin
      containers:
        - name: goautowp-autoban
          image: registry.pereslegin.ru/autowp/goautowp:v1.40.0
          imagePullPolicy: Always
          args:
            - autoban
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml
              readOnly: true
            - mountPath: /model.conf
              name: casbin
              subPath: model.conf
              readOnly: true
            - mountPath: /policy.csv
              name: casbin
              subPath: policy.csv
              readOnly: true
          resources:
            limits:
              memory: 5Gi
              cpu: 4000m
            requests:
              memory: 10M
              cpu: 50m
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 101
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - goautowp-autoban
              weight: 100
