apiVersion: v1
data: {{ (tpl (.Files.Glob "configs/goautowp/*").AsConfig . ) | nindent 2 }}
kind: ConfigMap
metadata:
  name: goautowp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goautowp-serve-public
spec:
  selector:
    matchLabels:
      app: goautowp-serve-public
  replicas: 3
  template:
    metadata:
      labels:
        app: goautowp-serve-public
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/{goautowp,casbin}/*").AsConfig . ) | sha256sum }}
    spec:
      volumes:
        - configMap:
            defaultMode: 420
            name: goautowp
          name: config
        - configMap:
            defaultMode: 420
            name: casbin
          name: casbin
      containers:
        - name: goautowp-serve-public
          image: autowp/goautowp
          imagePullPolicy: Always
          args:
            - serve-public
          ports:
            - name: app-port
              containerPort: 8080
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml
              readOnly: true
            - mountPath: /model.conf
              name: casbin
              subPath: model.conf
              readOnly: true
            - mountPath: /policy.csv
              name: casbin
              subPath: policy.csv
              readOnly: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goautowp-serve-private
spec:
  selector:
    matchLabels:
      app: goautowp-serve-private
  replicas: 3
  template:
    metadata:
      labels:
        app: goautowp-serve-private
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/{goautowp,casbin}/*").AsConfig . ) | sha256sum }}
    spec:
      volumes:
        - configMap:
            defaultMode: 420
            name: goautowp
          name: config
        - configMap:
            defaultMode: 420
            name: casbin
          name: casbin
      containers:
        - name: goautowp-serve-private
          image: autowp/goautowp
          imagePullPolicy: Always
          args:
            - serve-private
          ports:
            - name: app-port
              containerPort: 8081
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml
              readOnly: true
            - mountPath: /model.conf
              name: casbin
              subPath: model.conf
              readOnly: true
            - mountPath: /policy.csv
              name: casbin
              subPath: policy.csv
              readOnly: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goautowp-listen-df-amqp
spec:
  selector:
    matchLabels:
      app: goautowp-listen-df-amqp
  replicas: 1
  template:
    metadata:
      labels:
        app: goautowp-listen-df-amqp
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/{goautowp,casbin}/*").AsConfig . ) | sha256sum }}
    spec:
      volumes:
        - configMap:
            defaultMode: 420
            name: goautowp
          name: config
        - configMap:
            defaultMode: 420
            name: casbin
          name: casbin
      containers:
        - name: goautowp-listen-df-amqp
          image: autowp/goautowp
          imagePullPolicy: Always
          args:
            - listen-df-amqp
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml
              readOnly: true
            - mountPath: /model.conf
              name: casbin
              subPath: model.conf
              readOnly: true
            - mountPath: /policy.csv
              name: casbin
              subPath: policy.csv
              readOnly: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goautowp-listen-monitoring-amqp
spec:
  selector:
    matchLabels:
      app: goautowp-listen-monitoring-amqp
  replicas: 3
  template:
    metadata:
      labels:
        app: goautowp-listen-monitoring-amqp
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/{goautowp,casbin}/*").AsConfig . ) | sha256sum }}
    spec:
      volumes:
        - configMap:
            defaultMode: 420
            name: goautowp
          name: config
        - configMap:
            defaultMode: 420
            name: casbin
          name: casbin
      containers:
        - name: goautowp-listen-monitoring-amqp
          image: autowp/goautowp
          imagePullPolicy: Always
          args:
            - listen-monitoring-amqp
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml
              readOnly: true
            - mountPath: /model.conf
              name: casbin
              subPath: model.conf
              readOnly: true
            - mountPath: /policy.csv
              name: casbin
              subPath: policy.csv
              readOnly: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goautowp-autoban
spec:
  selector:
    matchLabels:
      app: goautowp-autoban
  replicas: 1
  template:
    metadata:
      labels:
        app: goautowp-autoban
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/{goautowp,casbin}/*").AsConfig . ) | sha256sum }}
    spec:
      volumes:
        - configMap:
            defaultMode: 420
            name: goautowp
          name: config
        - configMap:
            defaultMode: 420
            name: casbin
          name: casbin
      containers:
        - name: goautowp-autoban
          image: autowp/goautowp
          imagePullPolicy: Always
          args:
            - autoban
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml
              readOnly: true
            - mountPath: /model.conf
              name: casbin
              subPath: model.conf
              readOnly: true
            - mountPath: /policy.csv
              name: casbin
              subPath: policy.csv
              readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: goautowp-serve-public
  name: goautowp-serve-public
spec:
  ports:
    - name: app-port
      port: 8080
      protocol: TCP
      targetPort: app-port
  selector:
    app: goautowp-serve-public
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: goautowp-serve-private
  name: goautowp-serve-private
spec:
  ports:
    - name: app-port
      port: 8081
      protocol: TCP
      targetPort: app-port
  selector:
    app: goautowp-serve-private
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: goautowp-scheduler-hourly
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ (tpl (.Files.Glob "configs/{backend,casbin}/*").AsConfig . ) | sha256sum }}
        spec:
          volumes:
            - configMap:
                defaultMode: 420
                name: goautowp
              name: config
            - configMap:
                defaultMode: 420
                name: casbin
              name: casbin
          containers:
            - name: goautowp-scheduler-hourly
              image: autowp/goautowp
              imagePullPolicy: Always
              args:
                - scheduler-hourly
              volumeMounts:
                - mountPath: /config.yaml
                  name: config
                  subPath: config.yaml
                  readOnly: true
                - mountPath: /model.conf
                  name: casbin
                  subPath: model.conf
                  readOnly: true
                - mountPath: /policy.csv
                  name: casbin
                  subPath: policy.csv
                  readOnly: true
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
