apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: maintenance
spec:
  schedule: "27 4 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ (tpl (.Files.Glob "configs/backend/*").AsConfig . ) | sha256sum }}
        spec:
          volumes:
          - configMap:
              defaultMode: 420
              name: backend
            name: config
          containers:
            - name: maintenance
              image: autowp/autowp
              imagePullPolicy: Always
              args:
                - ./zf
                - cron
                - daily-maintenance
              volumeMounts:
                - mountPath: /app/config/autoload/local.php
                  name: config
                  subPath: local.php
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
