apiVersion: batch/v1
kind: CronJob
metadata:
  name: maintenance
spec:
  schedule: "27 4 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ (tpl (.Files.Glob "configs/{backend,casbin}/*").AsConfig . ) | sha256sum }}
        spec:
          volumes:
          - configMap:
              defaultMode: 420
              name: backend
            name: config
          - configMap:
              defaultMode: 420
              name: casbin
            name: casbin
          containers:
            - name: maintenance
              image: autowp/autowp
              imagePullPolicy: Always
              args:
                - ./zf
                - cron
                - daily-maintenance
              volumeMounts:
                - mountPath: /app/config/autoload/local.php
                  name: config
                  subPath: local.php
                  readOnly: true
                - mountPath: /app/module/Application/config/model.conf
                  name: casbin
                  subPath: model.conf
                  readOnly: true
                - mountPath: /app/module/Application/config/policy.csv
                  name: casbin
                  subPath: policy.csv
                  readOnly: true
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
