apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  selector:
    matchLabels:
      app: memcached
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: memcached:1-alpine
          ports:
            - containerPort: 11211

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: memcached
  name: memcached
spec:
  ports:
    - name: app-port
      port: 11211
      protocol: TCP
      targetPort: 11211
  selector:
    app: memcached
  sessionAffinity: None
  type: ClusterIP
