apiVersion: v1
data: {{ (tpl (.Files.Glob "configs/mysql-backup/*").AsConfig . ) | nindent 2 }}
kind: ConfigMap
metadata:
  name: mysql-backup

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "30 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - configMap:
              defaultMode: 420
              name: mysql-backup
            name: config
          containers:
            - name: mysql-backup
              image: autowp/autowp-tools
              env:
              - name: MYSQL_ROOT_PASSWORD
                value: {{ .Values.mysql.rootPassword | quote }}
              command:
                - /bin/bash
              args:
                - -c
                - mysqldump --host=mysql -u{{ .Values.mysql.username }} -p{{ .Values.mysql.password|quote }} --set-gtid-purged=OFF --hex-blob autowp | gzip -f | s3cmd -c /.s3cfg put - "s3://{{ .Values.backup.s3Bucket }}/$(date +"%Y-%m-%d_%H-%M-%S").sql.gz" --acl-private --guess-mime-type --no-progress
              volumeMounts:
              - mountPath: /.s3cfg
                name: config
                subPath: .s3cfg
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
