apiVersion: v1
data: {{ (tpl (.Files.Glob "configs/mysql/*").AsConfig . ) | nindent 2 }}
kind: ConfigMap
metadata:
  name: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/mysql/*").AsConfig . ) | sha256sum }}
    spec:
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql
        - configMap:
            defaultMode: 420
            name: mysql
          name: config
      containers:
        - name: mysql
          image: mysql:8
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword | quote }}
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql
            - mountPath: /etc/mysql/conf.d/mysql.cnf
              name: config
              subPath: mysql.cnf
              readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  ports:
    - name: app-port
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: ClusterIP
