apiVersion: v1
data: {{ (tpl (.Files.Glob "configs/rabbitmq/*").AsConfig . ) | nindent 2 }}
kind: ConfigMap
metadata:
  name: rabbitmq

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/rabbitmq/*").AsConfig . ) | sha256sum }}
    spec:
      volumes:
        - name: rabbitmq
          persistentVolumeClaim:
            claimName: rabbitmq
        - configMap:
            defaultMode: 420
            name: rabbitmq
          name: config
      containers:
        - name: rabbitmq
          image: rabbitmq:3-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 11211
          env:
            - name: RABBITMQ_LOGS
              value: "false"
          volumeMounts:
            - mountPath: "/var/lib/rabbitmq"
              name: rabbitmq
            - mountPath: /etc/rabbitmq/rabbitmq.conf
              name: config
              subPath: rabbitmq.conf

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: app-port
      port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    app: rabbitmq
  sessionAffinity: None
  type: ClusterIP
