{{- range .Values.redirects }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redirect-{{ .to }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: letsencrypt
    nginx.ingress.kubernetes.io/permanent-redirect: $scheme://{{ .to }}$request_uri
spec:
  tls:
    - hosts:
        {{- range .from }}
        - {{ . }}
        {{- end }}
      secretName: tls-redirect-{{ .to }}
  rules:
    {{- range .from }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: app-port
    {{- end }}
{{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: letsencrypt
spec:
  tls:
    - hosts:
        {{- range .Values.hostnames }}
        - {{ . }}
        {{- end }}
      secretName: tls
  rules:
  {{- range .Values.hostnames }}
  - host: {{ . }}
    http:
      paths:
        - path: /api/oauth/
          pathType: Prefix
          backend:
            service:
              name: auth
              port:
                number: 8080
  {{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    cert-manager.io/issuer: letsencrypt
spec:
  tls:
    - hosts:
        {{- range .Values.hostnames }}
        - {{ . }}
        {{- end }}
      secretName: tls
  rules:
  {{- range .Values.hostnames }}
  - host: {{ . }}
    http:
      paths:
        - path: /api/
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                name: app-port
        - path: /pictures/
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                name: app-port
        - path: /img/
          pathType: Prefix
          backend:
            service:
              name: static
              port:
                number: 80
  {{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goautowp
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: letsencrypt
spec:
  tls:
    - hosts:
        {{- range .Values.hostnames }}
        - {{ . }}
        {{- end }}
      secretName: tls
  rules:
  {{- range .Values.hostnames }}
  - host: {{ . }}
    http:
      paths:
        - path: /api/acl/is-allowed
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: /api/brands/icons
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: /api/comment/votes
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: /api/contacts
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: /api/feedback
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: /api/ip
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: /api/perspective
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: /api/recaptcha
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: /api/traffic
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: /api/vehicle-types
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
  {{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: letsencrypt
spec:
  tls:
    - hosts:
        {{- range .Values.hostnames }}
        - {{ . }}
        {{- end }}
      secretName: tls
  rules:
  {{- range .Values.hostnames }}
  - host: {{ . }}
    http:
      paths:
        - backend:
            service:
              name: frontend
              port:
                number: 80
          path: /
          pathType: Prefix
  {{- end }}
