{{- range .Values.redirects }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redirect-{{ .to }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/permanent-redirect: $scheme://{{ .to }}$request_uri
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        {{- range .from }}
        - {{ . }}
        {{- end }}
      secretName: tls-redirect-{{ .to }}
  rules:
    {{- range .from }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: app-port
    {{- end }}
{{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        {{- range .Values.hostnames }}
        - {{ . }}
        {{- end }}
      secretName: tls
  rules:
  {{- range .Values.hostnames }}
  - host: {{ . }}
    http:
      paths:
        - path: /api/
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                name: app-port
        - path: /pictures/
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                name: app-port
        - path: /img/
          pathType: Prefix
          backend:
            service:
              name: static
              port:
                number: 80
        - path: /api/oauth/
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: "/goautowp.Autowp/"
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: "/goautowp.Traffic/"
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: "/goautowp.Contacts/"
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: "/goautowp.Users/"
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: "/goautowp.Items/"
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: "/goautowp.Comments/"
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: "/goautowp.Map/"
          pathType: Prefix
          backend:
            service:
              name: goautowp-serve-public
              port:
                name: app-port
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 80
  {{- end }}
