apiVersion: v1
data: {{ (tpl (.Files.Glob "configs/traffic/*").AsConfig . ) | nindent 2 }}
kind: ConfigMap
metadata:
  name: traffic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic
spec:
  selector:
    matchLabels:
      app: traffic
  replicas: 1
  template:
    metadata:
      labels:
        app: traffic
      annotations:
        checksum/config: {{ (tpl (.Files.Glob "configs/traffic/*").AsConfig . ) | sha256sum }}
    spec:
      volumes:
        - configMap:
            defaultMode: 420
            name: traffic
          name: config
      containers:
        - name: traffic
          image: autowp/traffic
          imagePullPolicy: Always
          ports:
            - name: app-port
              containerPort: 8080
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: traffic
  name: traffic
spec:
  ports:
    - name: app-port
      port: 8080
      protocol: TCP
      targetPort: app-port
  selector:
    app: traffic
  sessionAffinity: None
  type: ClusterIP
