rabbitmq: amqp://guest:guest@{{ include "autowp.rabbitmq.fullname" . }}:5672/
sentry:
  dsn: {{ .Values.traffic.sentry.dsn | quote }}
  environment: production
dsn: postgres://{{ .Values.traffic.postgres.username }}:{{ .Values.traffic.postgres.password }}@{{ .Values.postgres.hostname }}:{{ .Values.postgres.port }}/traffic?sslmode=disable
migrations:
  dsn: postgres://{{ .Values.traffic.postgres.username }}:{{ .Values.traffic.postgres.password }}@{{ .Values.postgres.hostname }}/traffic?sslmode=disable
